name: CI Pipeline Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://test_user:test_password@localhost:5432/test_db"
      SECRET_KEY: "uma_chave_secreta_para_testes"

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # O requirements.txt está na raiz do repositório, então não precisa de prefixo
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest